version: '3'

services:
  jupyter-lab:
    build:
      context: .
    container_name: elsevier-ml-workshop
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/elsevier-ml-workshop/notebooks
      - ./data:/elsevier-ml-workshop/data
      - ./img:/elsevier-ml-workshop/img
    networks:
      - workshop-network

networks:
  workshop-network: